### ISSUE TITLE
什么时候支持php客户端呢？

### ISSUE THREAD

**Issue by pypypystudy** [hprose/hprose-workerman#1]

**Comment by IngwiePhoenix** [comment]
Sorry, I only understand German and English.

@andot Could you help me here, maybe?

**Comment by pypypystudy** [comment]
what's the plan to support php client ?

**Comment by IngwiePhoenix** [comment]
hprose has gotten quite the updaes since I started this project here. You could try to connect using TCP. There should be a pure TcpClient in PHP that you can leverage in the client. If it turns out to work for you, let me know. :)

**Comment by pypypystudy** [comment]
ok, Thank you for your reply.  :)

**Comment by IngwiePhoenix** [comment]
Very welcome. :) If you have further questions, go ahead. I use this project in production, and in fact, am the one responsible for this "port" of hprose to work with Workerman. ^^

Happy coding!
